# Generated by Django 5.1.15 on 2026-10-03 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DetectorModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='название')),
                ('description', models.TextField(blank=True, verbose_name='описание')),
                ('note', models.TextField(blank=True, verbose_name='примечание')),
                ('file', models.FileField(upload_to='models/', verbose_name='файл')),
                ('is_active', models.BooleanField(default=True, verbose_name='активна')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'модель',
                'verbose_name_plural': 'модели',
                'ordering': ['-updated_at'],
            },
        ),
    ]
