# Generated by Django 5.1.15 on 2026-10-03 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='detectormodel',
            name='labels',
            field=models.TextField(blank=True, help_text='JSON-список имён карт в порядке модели', verbose_name='классы'),
        ),
        migrations.AlterField(
            model_name='detectormodel',
            name='file',
            field=models.FileField(help_text='формат .onnx, его запускает телефон', upload_to='models/', verbose_name='файл'),
        ),
    ]
