# Generated by Django 5.1.15 on 2026-10-03 21:10

from django.db import migrations, models


def mark_ready(apps, schema_editor):
    """Модели, загруженные до появления конвертера, уже лежат в .onnx."""
    DetectorModel = apps.get_model("catalog", "DetectorModel")
    DetectorModel.objects.exclude(file="").update(status="ready")


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_detectormodel_labels_alter_detectormodel_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='detectormodel',
            name='error',
            field=models.TextField(blank=True, verbose_name='ошибка конвертации'),
        ),
        migrations.AddField(
            model_name='detectormodel',
            name='source_file',
            field=models.FileField(blank=True, help_text='то, что принёс администратор: .pt или .onnx', upload_to='sources/', verbose_name='загруженный файл'),
        ),
        migrations.AddField(
            model_name='detectormodel',
            name='status',
            field=models.CharField(choices=[('pending', 'готовится'), ('ready', 'готова'), ('failed', 'ошибка')], default='pending', max_length=10, verbose_name='состояние'),
        ),
        migrations.AlterField(
            model_name='detectormodel',
            name='file',
            field=models.FileField(blank=True, help_text='.onnx, его готовит сервер', upload_to='models/', verbose_name='файл для телефона'),
        ),
        migrations.RunPython(mark_ready, migrations.RunPython.noop),
    ]
